session/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # READ
    path('', views.home, name='home'),  # 127.0.0.1:8000
    path('blog/<int:blog_id>/', views.detail, name='detail'),
    # CREATE
    path('blog/new/', views.new, name='new'),
    path('blog/create/', views.create, name='create'),
    # UPDATE
    path('blog/edit/<int:blog_id>/', views.edit, name='edit'),
    path('blog/update/<int:blog_id>/', views.update, name='update'),
    # DELETE
    path('blog/delete/<int:blog_id>/', views.delete, name='delete'),
    # COMMENT
    path('blog/new_comment/<int:blog_id>/',
         views.new_comment, name='new_comment'),
    path('blog/create_comment/<int:blog_id>/',
         views.create_comment, name='create_comment'),
    # LIKE
    path('blog/<int:blog_id>/like',
         views.like, name='like'),
]

session/session/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 127.0.0.1:8000/blog

session/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    path('new_profile/', new_profile, name='new_profile'),
    path('create_profile/', create_profile, name='create_profile'),
]

session/blog/models.py
from django.db import models
from users.models import CustomUser


class Blog(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/', null=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)
    tag = models.ManyToManyField('Tag', blank=True)

    class Meta:
        db_table = 'blog'

    def __str__(self):
        return self.title + ' | ' + str(self.author)

    def summary(self):
        return self.content[:100]


class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'comment'

    def __str__(self):
        return self.content + ' | ' + str(self.author)


class Tag(models.Model):
    name = models.CharField(max_length=20)

    class Meta:
        db_table = 'tag'

    def __str__(self):
        return self.name


class Like(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True)
    likedUser = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = 'like'

    def __str__(self):
        return self.blog.title + ' | ' + str(self.likedUser)

session/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content']

session/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Blog, Comment, Tag, Like


def home(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'home.html', {'page_obj': page_obj})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comments = Comment.objects.filter(blog=blog)
    tags = blog.tag.all()
    likes = len(Like.objects.filter(blog=blog))

    return render(request, 'detail.html', {'blog': blog, 'comments': comments, 'tags': tags, 'likes':likes,})


def new(request):
    tags = Tag.objects.all()
    return render(request, 'new.html', {'tags': tags})


def create(request):
    new_blog = Blog()
    new_blog.title = request.POST.get('title')
    new_blog.content = request.POST.get('content')
    new_blog.image = request.FILES.get('image')
    new_blog.author = request.user

    new_blog.save()
    tags = request.POST.getlist('tags')

    for tag_id in tags:
        tag = Tag.objects.get(id=tag_id)
        new_blog.tag.add(tag)

    return redirect('detail', new_blog.id)


def edit(request, blog_id):
    # edit_blog = get_object_or_404(Blog, pk=blog_id)
    edit_blog = Blog.objects.get(id=blog_id)

    if request.user != edit_blog.author:
        return redirect('home')

    return render(request, 'edit.html', {'edit_blog': edit_blog})


def update(request, blog_id):
    old_blog = get_object_or_404(Blog, pk=blog_id)
    old_blog.title = request.POST.get('title')
    old_blog.content = request.POST.get('content')
    old_blog.image = request.FILES.get('image')
    old_blog.save()
    return redirect('detail', old_blog.id)


def delete(request, blog_id):
    delete_blog = get_object_or_404(Blog, pk=blog_id)
    if request.user == delete_blog.author:
        delete_blog.delete()
        return redirect('home')
    return redirect('detail', delete_blog.id)


def create_comment(request, blog_id):
    comment = Comment()
    comment.content = request.POST.get('content')
    comment.blog = get_object_or_404(Blog, pk=blog_id)
    comment.author = request.user
    comment.save()
    return redirect('detail', blog_id)


def new_comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'new_comment.html', {'blog': blog})


def like(request, blog_id):
    # 비로그인시 좋아요 못누르고 로그인하기로 이동
    if request.user.is_anonymous:
        return redirect("users:signin")
    # 좋아요 한 적이 있으면 detail path로 이동
    if Like.objects.filter(likedUser=request.user, blog_id=blog_id):
        return redirect("detail", blog_id)
    # 좋아요 한 적 없으면 Like 객체 만들기
    like = Like()
    like.blog = get_object_or_404(Blog, pk=blog_id)
    like.likedUser = request.user
    like.save()
    return redirect('detail', blog_id)

session/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    {% block extrahead %} {% endblock extrahead %}
  </head>

  <body>
    {% block content %} {% endblock content %}
  </body>
</html>

session/blog/templates/detail.html
<h1>블로그 상세 페이지</h1>
<br/>
<hr/>
<h2>{{blog.title}}</h2>
<hr/>
{% if tags %}
  <h2>태그</h2>
  <div style="display: flex">
    {% for tag in tags %}
      <p>{{ tag }}</p>&nbsp;
    {% endfor %}
  </div>
{% endif %}

<hr/>
<p>{{blog.content}}</p>

{% if blog.image %}
  <img src="{{blog.image.url}}" alt="이미지"/>
{% endif %}

<p>{{blog.created_at}}</p>

<a href="{% url 'home' %}">홈</a>
<a href="{% url 'edit' blog.id %}">수정하기</a>
<a href="{% url 'delete' blog.id %}">삭제하기</a>
<a href="{% url 'new_comment' blog.id %}">댓글 달기</a>
<a href="{%url 'like' blog.id%}">좋아요</a>
<span>좋아요 개수:
  {{likes}}</span>

{% for comment in comments %}
  <hr/>
  <p>{{comment.content}}</p>
  <p>{{comment.created_at}}
    댓글쓴이:
    {{ comment.author }}</p>
{% endfor %}

session/blog/templates/edit.html
<h1>edit 페이지</h1>

<form method="POST" action="{% url 'update' edit_blog.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title" value="{{edit_blog.title}}" />
    <textarea name="content" id="" cols="30">{{edit_blog.content}}</textarea>
    <input type="file" name="image" />
    <input type="submit" value="수정하기" />
</form>

<a href="{% url 'home' %}">홈</a>
<a href="{% url 'delete' edit_blog.id %}">삭제하기</a>

session/blog/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  블로그 홈페이지!!
{% endblock title %}
{% block extrahead %}
  <link rel="stylesheet" href="{% static 'blog/css/style.css' %}"/>
{% endblock extrahead %}
{% block content %}

  <h1>
    LIKELION 11 Blog Project
    <img src="{% static 'blog/img/emoticon.png' %}" alt="이모티콘"/>
  </h1>

  <a href="{% url 'users:new_profile'%}">마이페이지</a>
  <div>
    {% if user.is_authenticated %}
      <a href="{% url 'users:signout' %}">로그아웃</a>
      <h1>환영합니다!
        {{user.username}}
        님</h1>
      <a class="new-post__button" href="{% url 'new' %}">새 글 작성하기</a>
    {% else %}
      <a href="{% url 'users:signup' %}">회원가입</a>
      <a href="{% url 'users:signin' %}">로그인</a>
    {% endif %}
  </div>
  <div>
    {% for blog in page_obj %}
      <a href="{%url 'detail' blog.id %}">
        <h2>{{blog.title}}</h2>
        <p>글쓴이:
          {{blog.author}}</p>
        <p>{{blog.summary}}</p>
        <p>{{blog.created_at}}</p>
      </a>
    {% endfor %}
  </div>

  <span>
    {% if page_obj.has_previous %}
      <a href="?page=1">처음으로</a>
      <a href="?page={{page_obj.previous_page_number}}">이전</a>
    {% endif %}

    <p>{{page_obj.number}}</p>
    <p>/</p>
    <p>{{page_obj.paginator.num_pages}}</p>

    {% if page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}">다음</a>
      <a href="?page={{page_obj.paginator.num_pages}}">마지막으로</a>
    {% endif %}
  </span>
{% endblock content %}

session/blog/templates/new.html
<h1>새 글 작성하기</h1>
<form action="{%url 'create'%}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    제목 : <input type="text" name="title" value="" />
    본문 : <textarea name="content" id="" cols="30" rows="10"></textarea>
    사진 : <input type="file" name="image" />

    <label for="tags">Tags:</label>
    <select name="tags" id="tags" multiple>
      {% for tag in tags %}
        <option value="{{ tag.id }}">{{ tag.name }}</option>
      {% endfor %}
    </select>
    <input type="submit" value="작성하기" />
</form>

<a href="{% url 'home' %}">홈</a>

session/blog/templates/new_comment.html
<h1>새 댓글 작성하기</h1>
<form
  action="{%url 'create_comment' blog.id %}"
  method="POST"
  enctype="multipart/form-data"
>
  {% csrf_token %} 댓글 :
  <textarea name="content" id="" cols="30" rows="10"></textarea>
  <input type="submit" value="댓글 달기" />
</form>

<a href="{% url 'home' %}">홈</a>