session/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # READ
    path('', views.home, name='home'),  # 127.0.0.1:8000
    path('blog/<int:blog_id>/', views.detail, name='detail'),
    # CREATE
    path('blog/new/', views.new, name='new'),
    path('blog/create/', views.create, name='create'),
    # UPDATE
    path('blog/edit/<int:blog_id>/', views.edit, name='edit'),
    path('blog/update/<int:blog_id>/', views.update, name='update'),
    # DELETE
    path('blog/delete/<int:blog_id>/', views.delete, name='delete'),
    # COMMENT
    path('blog/new_comment/<int:blog_id>/',
         views.new_comment, name='new_comment'),
    path('blog/create_comment/<int:blog_id>/',
         views.create_comment, name='create_comment'),
    # LIKE
    path('blog/<int:blog_id>/like',
         views.like, name='like'),
]

session/session/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 127.0.0.1:8000/blog

session/users/urls.py
from django.urls import path
from .views import *

app_name = 'users'

urlpatterns = [
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('signout/', signout, name='signout'),
    path('new_profile/', new_profile, name='new_profile'),
    path('create_profile/', create_profile, name='create_profile'),
]

session/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class CustomUserManager(BaseUserManager):
    def create_user(self, username, password, **kwargs): # 필수
        user = self.model(username=username, **kwargs)
        user.set_password(password)
        user.save()
        
    def create_normaluser(self, username, password, **kwargs): # 필수
        self.create_user(username, password, **kwargs)
        
    def create_superuser(self, username, password, **kwargs): # 필수
        kwargs.setdefault("is_superuser", True)
        self.create_user(username, password, **kwargs)
class CustomUser( AbstractBaseUser, PermissionsMixin):
    objects = CustomUserManager()
    
    USERNAME_FIELD = "username"
    
    username = models.CharField(unique=True, max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # 원래 장고 기본 모델에서 제공해주는 기능. 
    @property
    def is_staff(self):
        return self.is_superuser

class Profile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, null=True)
    nickname = models.CharField(max_length=20, null=True)
    image = models.ImageField(upload_to='profile/', null=True)

    class Meta:
        db_table = 'profile'

    def __str__(self):
        return self.nickname

session/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser


class CustomUserSignupForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ['username']


class CustomUserSigninForm(AuthenticationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ['username']

session/users/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Profile
from django.shortcuts import render, redirect
from .forms import CustomUserSigninForm, CustomUserSignupForm

# # 회원가입
# def signup(request):
#     if request.method == 'POST':
#         if request.POST['password1'] == request.POST['password2']:
#             user = User.objects.create_user(
#                 username=request.POST['username'],
#                 password=request.POST['password1'],
#                 email=request.POST['email'],)
#             profile = Profile(user=user, nickname=request.POST['nickname'], image=request.FILES.get('profile_image'))
#             profile.save()

#             auth.login(request, user)
#             return redirect('/')
#         return render(request, 'signup.html')
#     return render(request, 'signup.html')

# # 로그인
# def login(request):
#     if request.method == 'POST':
#         username = request.POST['username']
#         password = request.POST['password']
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             auth.login(request, user)
#             return redirect('/')
#         else:
#             return render(request, 'login.html')
#     else:
#         return render(request, 'login.html')

# # 로그아웃
# def logout(request):
#   auth.logout(request)
#   return redirect('home')


def signup(request):
    form = CustomUserSignupForm()
    # good user
    if request.method == "POST":
        form =CustomUserSignupForm(request.POST)
        if form.is_valid():
            user = form.save() # 튜플 폼데이터를 DB에 저장
            login(request, user)
            return redirect('home')
    # bad user
    return render(request, "newSignup.html", {"form" : form})

def signin(request):
    form = CustomUserSigninForm()
    # good user
    if request.method == "POST":
        form = CustomUserSigninForm(request, request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('home')
    # bad user
    return  render(request, "newSignin.html", {"form" : form})

def signout(request):
    logout(request)
    return redirect('home')

def new_profile(request):
    # 로그인 하지 않았다면 프로필 눌러도 홈으로 이동
    if request.user.is_anonymous:
        return redirect('home')
    # 로그인 했다면 해당 유저의 프로필 보기
    profile, created = Profile.objects.get_or_create(user=request.user)
    return render(request, 'newProfile.html', {"profile":profile})
    # 프로필이 원래 존재했으면 created=False
    
def create_profile(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    if request.method == "POST":
        profile.nickname = request.POST.get('nickname')
        profile.image = request.FILES.get('image')
        profile.save()
        return redirect('users:new_profile')
    return render(request, "newProfile.html", {'profile':profile})

session/users/templates/login.html
{% extends 'base.html' %} {% block content %}
<div class="wrapper">
  <div style="text-align: center">
    <h1>로그인</h1>
    <form method="POST">
      {% csrf_token %} 아이디:
      <br />
      <input name="username" type="text" />
      <br />
      비밀번호:
      <br />
      <input name="password" type="password" />
      <br /><br />
      <input type="submit" class="btn btn-primary" value="Login" />
    </form>
  </div>
</div>
{% endblock %}

session/users/templates/newProfile.html
<h1>프로필</h1>
<hr>

<h2>계정정보</h2>
<p>아이디:
  {{user.username}}</p>
<hr>

<h2>프로필 정보</h2>
<form method='POST' ,="," enctype='multipart/form-data' action="{% url 'users:create_profile' %}">{% csrf_token %}
  <label for="nickname">닉네임:</label>
  <input type='text' name='nickname' id='nickname' value="{{profile.nickname}}"/><br><br>
  <label for="image">프로필 사진:</label>
  {% if profile.image %}
    <img src="{{profile.image.url}}" alt="프로필사진" width="100">
    <br>
    <label>
      <input type='checkbox' name='remove_image'/>사진삭제</label>
    <br><br>
    {%endif%}
    <input type="file" name="image" id="image"/><br><br>
    <button type="submit">저장</button>
  </form>

  <a href="{% url 'home' %}">홈</a>

session/users/templates/newSignin.html
<h1>Signin page</h1>

<form method="POST" action="{% url 'users:signin' %}">
  {% csrf_token %}
  {{ form }}
    <input type='submit' value="signin"/>
  </form>

  <a href="{%url 'home'%}">home</a>

session/users/templates/newSignup.html
<h1>Signup page</h1>

<form method="POST" action="{% url 'users:signup' %}">
  {% csrf_token %}
  {{ form }}
    <input type='submit' value="signup"/>
  </form>

  <a href="{%url 'home'%}">home</a>

session/users/templates/signup.html
{% extends 'base.html' %} {% block content %}
<div class="wrapper" style="text-align: center">
  <h1>회원가입</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %} 아이디: <br />
    <input name="username" type="text" />
    <br />
    비밀번호: <br />
    <input name="password1" type="password" />
    <br />
    비밀번호 확인: <br />
    <input name="password2" type="password" />
    <br />
    이메일: <br />
    <input name="email" type="email" />
    <br />
    닉네임: <br />
    <input name="nickname" type="text" />
    <br /><br />
    사진 : <input type="file" name="profile_image" />
    <br />
    <input type="submit" class="btn btn-primary" value="Sign Up" />
  </form>
</div>
{% endblock %}